// <auto-generated />
using System;
using BillSplit.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillSplit.Persistence.Migrations
{
    [DbContext(typeof(BillsplitContext))]
    [Migration("20230215204309_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billsplit")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillSplit.Domain.Models.Bill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<long>("BillGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("PaidBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BillGroupId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("PaidBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Bill", "billsplit");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.BillAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<long>("BillId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("BillAllocation", "billsplit");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.BillGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("BillGroup", "billsplit");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("User", "billsplit");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.UserBillGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("BillGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillGroupId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex(new[] { "UserId", "BillGroupId" }, "UserBillGroup_UserId_BillGroupId_uindex")
                        .IsUnique();

                    b.ToTable("UserBillGroup", "billsplit");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "billsplit");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "billsplit");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "billsplit");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.Bill", b =>
                {
                    b.HasOne("BillSplit.Domain.Models.BillGroup", "BillGroup")
                        .WithMany("Bills")
                        .HasForeignKey("BillGroupId")
                        .IsRequired()
                        .HasConstraintName("Bill_BillGroup_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "CreatedByNavigation")
                        .WithMany("BillCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("Bill_Created_By_User_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "DeletedByNavigation")
                        .WithMany("BillDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("Bill_Deleted_By_User__fk");

                    b.HasOne("BillSplit.Domain.Models.User", "PaidByNavigation")
                        .WithMany("BillPaidByNavigations")
                        .HasForeignKey("PaidBy")
                        .IsRequired()
                        .HasConstraintName("Bill_Paid_By_User_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "UpdatedByNavigation")
                        .WithMany("BillUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("Bill_Updated_By_User__fk");

                    b.Navigation("BillGroup");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("PaidByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.BillAllocation", b =>
                {
                    b.HasOne("BillSplit.Domain.Models.Bill", "Bill")
                        .WithMany("BillAllocations")
                        .HasForeignKey("BillId")
                        .IsRequired()
                        .HasConstraintName("BillAllocation_Bill_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "CreatedByNavigation")
                        .WithMany("BillAllocationCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("BillAllocation_Created_By_User_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "DeletedByNavigation")
                        .WithMany("BillAllocationDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("BillAllocation_Deleted_By_User__fk");

                    b.HasOne("BillSplit.Domain.Models.User", "UpdatedByNavigation")
                        .WithMany("BillAllocationUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("BillAllocation_Updated_By_User__fk");

                    b.HasOne("BillSplit.Domain.Models.User", "User")
                        .WithMany("BillAllocationUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("BillAllocation_User_Id_fk");

                    b.Navigation("Bill");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("UpdatedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.BillGroup", b =>
                {
                    b.HasOne("BillSplit.Domain.Models.User", "CreatedByNavigation")
                        .WithMany("BillGroupCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("BillGroup_Created_By_User_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "DeletedByNavigation")
                        .WithMany("BillGroupDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("BillGroup_Deleted_By_User_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "UpdatedByNavigation")
                        .WithMany("BillGroupUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("BillGroup_Updated_By_User_Id_fk");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.User", b =>
                {
                    b.HasOne("BillSplit.Domain.Models.User", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("User_Created_By_User_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "DeletedByNavigation")
                        .WithMany("InverseDeletedByNavigation")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("User_Deleted_By_User__fk");

                    b.HasOne("BillSplit.Domain.Models.User", "UpdatedByNavigation")
                        .WithMany("InverseUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("User_Updated_By_User__fk");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.UserBillGroup", b =>
                {
                    b.HasOne("BillSplit.Domain.Models.BillGroup", "BillGroup")
                        .WithMany("UserBillGroups")
                        .HasForeignKey("BillGroupId")
                        .IsRequired()
                        .HasConstraintName("UserBillGroup_Bill_Group_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "CreatedByNavigation")
                        .WithMany("UserBillGroupCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("UserBillGroup_Created_By_User_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "DeletedByNavigation")
                        .WithMany("UserBillGroupDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("UserBillGroup_Deleted_By_User_Id_fk");

                    b.HasOne("BillSplit.Domain.Models.User", "User")
                        .WithMany("UserBillGroupUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("UserBillGroup_User_Id_fk");

                    b.Navigation("BillGroup");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("BillSplit.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("BillSplit.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("BillSplit.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BillSplit.Domain.Models.Bill", b =>
                {
                    b.Navigation("BillAllocations");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.BillGroup", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("UserBillGroups");
                });

            modelBuilder.Entity("BillSplit.Domain.Models.User", b =>
                {
                    b.Navigation("BillAllocationCreatedByNavigations");

                    b.Navigation("BillAllocationDeletedByNavigations");

                    b.Navigation("BillAllocationUpdatedByNavigations");

                    b.Navigation("BillAllocationUsers");

                    b.Navigation("BillCreatedByNavigations");

                    b.Navigation("BillDeletedByNavigations");

                    b.Navigation("BillGroupCreatedByNavigations");

                    b.Navigation("BillGroupDeletedByNavigations");

                    b.Navigation("BillGroupUpdatedByNavigations");

                    b.Navigation("BillPaidByNavigations");

                    b.Navigation("BillUpdatedByNavigations");

                    b.Navigation("InverseCreatedByNavigation");

                    b.Navigation("InverseDeletedByNavigation");

                    b.Navigation("InverseUpdatedByNavigation");

                    b.Navigation("UserBillGroupCreatedByNavigations");

                    b.Navigation("UserBillGroupDeletedByNavigations");

                    b.Navigation("UserBillGroupUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
