// <auto-generated />
using System;
using BillSplit.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillSplit.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20221223190848_InitialUserTable")]
partial class InitialUserTable
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("billsplit")
            .HasAnnotation("ProductVersion", "7.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("BillSplit.Infrastructure.Entities.UserEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<long?>("CreatedBy")
                    .HasColumnType("bigint");

                b.Property<DateTime>("CreatedDate")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<long?>("DeletedBy")
                    .HasColumnType("bigint");

                b.Property<DateTime?>("DeletedDate")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)");

                b.Property<bool>("IsSuperUser")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<long>("PhoneNumber")
                    .HasColumnType("bigint");

                b.Property<long?>("UpdatedBy")
                    .HasColumnType("bigint");

                b.Property<DateTime>("UpdatedDate")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.HasKey("Id");

                b.ToTable("User", "billsplit");
            });
#pragma warning restore 612, 618
    }
}
